---
apiVersion: v1
kind: Namespace
metadata:
  name: prometheus

---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: prometheus
spec:
  interval: 24h
  url: https://prometheus-community.github.io/helm-charts

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-community
  namespace: prometheus
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
  interval: 2m
  install:
    remediation:
      retries: 3
#  uninstall:
#    #    timeout: 24h
#    disableHooks: false
#    keepHistory: false
#  values:
#    clusterName: demo
#    serviceAccount:
#      create: false
#      name: aws-load-balancer-controller
##      name: cluster-autoscaler
